### ISSUE TITLE
Can remix coins be unconfirmed?

### ISSUE THREAD

**Issue by MaxHillebrand** [nopara73/Yohohoho#7]
In the **Inpute Registration Phase**, the paper says `These inputs must be unspent, confirmed and mature.`

However, in current zero link, because of the segwit malleability fix, previous CoinJoin outputs CAN be unconfirmed at the point when they are registered for re-mixing. 

Is this possible in the new scheme too?

**Comment by nopara73** [comment]
We'll go with the assumption that they cannot and may relax it later.
